export type StateEngineErrorCode =
  | "COMMAND_INVALID"
  | "COMMAND_NOT_SUPPORTED"
  | "STATE_REVISION_CONFLICT"
  | "STATE_SAVE_MISMATCH"
  | "STATE_VALIDATION_FAILED"
  | "MUTATION_PATH_INVALID"
  | "MUTATION_BEFORE_MISMATCH"
  | "CHARACTER_NOT_FOUND"
  | "OFFICE_NOT_FOUND"
  | "OFFICE_OCCUPIED"
  | "MEETING_NOT_FOUND"
  | "MEETING_INVALID_STATE"
  | "MEETING_ALREADY_STARTED"
  | "MEETING_ALREADY_CONCLUDED"
  | "MEETING_PARTICIPANT_INVALID"
  | "POLICY_NOT_FOUND"
  | "POLICY_TEMPLATE_NOT_FOUND"
  | "POLICY_STATUS_INVALID"
  | "POLICY_TRANSITION_INVALID"
  | "POLICY_ALREADY_DECIDED"
  | "POLICY_COST_INSUFFICIENT"
  | "POLICY_ASSIGNEE_INVALID"
  | "POLICY_LEGALITY_BLOCKED";

export class StateEngineError extends Error {
  constructor(
    readonly code: StateEngineErrorCode,
    message: string,
    readonly details?: unknown,
  ) {
    super(message);
    this.name = "StateEngineError";
  }
}
