import type { PromptId, PromptManifestEntry } from "./types";

/**
 * Prompt Manifest（ADR-013）：每个资产的用途、变量与标签的唯一登记处。
 * 测试保证：manifest 与 prompt-loader 注册表一一对应；
 * requiredVariables 与资产内 {{变量}} 一致。
 */
export const PROMPT_MANIFEST: readonly PromptManifestEntry[] = [
  {
    id: "system.base",
    version: "v1",
    file: "system/base.v1.md",
    purpose: "Phase 1 叙事系统基础提示",
    requiredVariables: ["scenarioName"],
    optionalVariables: [],
    tags: ["system", "legacy"],
  },
  {
    id: "system.character-agent-base",
    version: "v1",
    file: "system/character-agent-base.v1.md",
    purpose: "Character Agent 安全边界与职责总纲（组合序 1）",
    requiredVariables: ["scenarioName", "currentDate", "characterName"],
    optionalVariables: [],
    maxRecommendedCharacters: 2_000,
    tags: ["system", "character-agent", "safety"],
  },
  {
    id: "character.identity",
    version: "v1",
    file: "character/identity.v1.md",
    purpose: "人物身份数据段（组合序 3）",
    requiredVariables: ["identityData"],
    optionalVariables: [],
    tags: ["character-agent", "data"],
  },
  {
    id: "character.personality",
    version: "v1",
    file: "character/personality.v1.md",
    purpose: "人格与行事倾向数据段（组合序 4）",
    requiredVariables: ["personalityData"],
    optionalVariables: [],
    tags: ["character-agent", "data"],
  },
  {
    id: "character.political-profile",
    version: "v1",
    file: "character/political-profile.v1.md",
    purpose: "政治立场与利益数据段（组合序 4）",
    requiredVariables: ["politicalData"],
    optionalVariables: [],
    tags: ["character-agent", "data"],
  },
  {
    id: "character.communication-style",
    version: "v1",
    file: "character/communication-style.v1.md",
    purpose: "言语风格数据段（组合序 4）",
    requiredVariables: ["communicationData"],
    optionalVariables: [],
    tags: ["character-agent", "data"],
  },
  {
    id: "knowledge.known-world-state",
    version: "v1",
    file: "knowledge/known-world-state.v1.md",
    purpose: "角色有限知识视图数据段（组合序 6）",
    requiredVariables: ["knowledgeData"],
    optionalVariables: [],
    tags: ["character-agent", "data", "knowledge"],
  },
  {
    id: "context.private-audience",
    version: "v1",
    file: "context/private-audience.v1.md",
    purpose: "单独召见场合规则（组合序 5）",
    requiredVariables: ["participantsLabel", "topicLabel"],
    optionalVariables: [],
    tags: ["character-agent", "context"],
  },
  {
    id: "context.court-assembly",
    version: "v1",
    file: "context/court-assembly.v1.md",
    purpose: "大朝会场合规则（组合序 5）",
    requiredVariables: ["participantsLabel", "topicLabel"],
    optionalVariables: [],
    tags: ["character-agent", "context"],
  },
  {
    id: "context.imperial-council",
    version: "v1",
    file: "context/imperial-council.v1.md",
    purpose: "御前会议场合规则（组合序 5）",
    requiredVariables: ["participantsLabel", "topicLabel"],
    optionalVariables: [],
    tags: ["character-agent", "context"],
  },
  {
    id: "context.secret-council",
    version: "v1",
    file: "context/secret-council.v1.md",
    purpose: "秘密议事场合规则（组合序 5）",
    requiredVariables: ["participantsLabel", "topicLabel"],
    optionalVariables: [],
    tags: ["character-agent", "context"],
  },
  {
    id: "context.memorial-response",
    version: "v1",
    file: "context/memorial-response.v1.md",
    purpose: "奏疏应对场合规则（组合序 5）",
    requiredVariables: ["participantsLabel", "topicLabel"],
    optionalVariables: [],
    tags: ["character-agent", "context"],
  },
  {
    id: "context.general",
    version: "v1",
    file: "context/general.v1.md",
    purpose: "一般对答场合规则（组合序 5）",
    requiredVariables: ["participantsLabel", "topicLabel"],
    optionalVariables: [],
    tags: ["character-agent", "context"],
  },
  {
    id: "context.conversation-input",
    version: "v1",
    file: "context/conversation-input.v1.md",
    purpose: "当前对话输入（user 消息，组合序 8）",
    requiredVariables: ["conversationData"],
    optionalVariables: [],
    tags: ["character-agent", "conversation"],
  },
  {
    id: "memory.memory-context",
    version: "v1",
    file: "memory/memory-context.v1.md",
    purpose: "相关记忆数据段（组合序 7）",
    requiredVariables: ["memoryData"],
    optionalVariables: [],
    tags: ["character-agent", "data", "memory"],
  },
  {
    id: "memory.memory-candidate",
    version: "v1",
    file: "memory/memory-candidate.v1.md",
    purpose: "记忆候选产出规则（组合序 8 前）",
    requiredVariables: [],
    optionalVariables: [],
    tags: ["character-agent", "memory"],
  },
  {
    id: "output.character-response",
    version: "v1",
    file: "output/character-response.v1.md",
    purpose: "结构化输出格式契约（组合序 9）",
    requiredVariables: [],
    optionalVariables: [],
    outputSchemaId: "CharacterAgentModelOutput",
    tags: ["character-agent", "output"],
  },
  {
    id: "output.repair-structured-output",
    version: "v1",
    file: "output/repair-structured-output.v1.md",
    purpose: "结构化输出失败后的受控修复请求",
    requiredVariables: ["invalidOutput", "validationErrors"],
    optionalVariables: [],
    outputSchemaId: "CharacterAgentModelOutput",
    tags: ["character-agent", "output", "repair"],
  },
  {
    id: "meeting.court-assembly",
    version: "v1",
    file: "meeting/court-assembly.v1.md",
    purpose: "Phase 1 朝会占位提示（Phase 4 重构）",
    requiredVariables: ["scenarioName", "characterName", "topic"],
    optionalVariables: [],
    tags: ["meeting", "legacy"],
  },
  {
    id: "meeting.imperial-council",
    version: "v1",
    file: "meeting/imperial-council.v1.md",
    purpose: "Phase 1 御前会议占位提示（Phase 4 重构）",
    requiredVariables: ["scenarioName", "characterName", "topic"],
    optionalVariables: [],
    tags: ["meeting", "legacy"],
  },
  {
    id: "meeting.secret-council",
    version: "v1",
    file: "meeting/secret-council.v1.md",
    purpose: "Phase 1 秘密议事占位提示（Phase 4 重构）",
    requiredVariables: ["scenarioName", "characterName", "topic"],
    optionalVariables: [],
    tags: ["meeting", "legacy"],
  },
  {
    id: "parser.policy-draft",
    version: "v1",
    file: "parser/policy-draft.v1.md",
    purpose: "政策草案结构化提取（Phase 5 使用）",
    requiredVariables: ["policyText"],
    optionalVariables: [],
    tags: ["parser", "legacy"],
  },
  {
    id: "narrator.memorial-summary",
    version: "v1",
    file: "narrator/memorial-summary.v1.md",
    purpose: "奏疏摘要（Phase 6 使用）",
    requiredVariables: ["scenarioName", "memorialText"],
    optionalVariables: [],
    tags: ["narrator", "legacy"],
  },
];

export function getManifestEntry(id: PromptId): PromptManifestEntry {
  const entry = PROMPT_MANIFEST.find((value) => value.id === id);
  if (!entry) throw new Error(`Prompt manifest 缺少条目：${id}`);
  return entry;
}
